#!/usr/bin/env python3

import sys

from RPi import GPIO

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(26, GPIO.OUT)
GPIO.setup(19, GPIO.OUT)
GPIO.setup(13, GPIO.OUT)

GPIO.output(26, GPIO.HIGH)
GPIO.output(19, GPIO.HIGH)
GPIO.output(13, GPIO.HIGH)

try:
	if "r" in sys.argv[1]:
		GPIO.output(26, GPIO.LOW)

	if "g" in sys.argv[1]:
		GPIO.output(19, GPIO.LOW)

	if "b" in sys.argv[1]:
		GPIO.output(13, GPIO.LOW)
except:
	exit(0)

