#!/usr/bin/env python3

import sys

from RPi import GPIO

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(22, GPIO.OUT)

if sys.argv[1] == "1":
	GPIO.output(22, GPIO.HIGH)
else:
	GPIO.output(22, GPIO.LOW)




